/* Projeto Fitcard */


/* MODELAGEM CONCEITUAL */
/*
ESTABELECIMENTO

RAZÃO SOCIAL - CARACTER(70) - OBRIGATORIO
NOME FANTASIA - CARACTER(70)
CNPJ - CARACTER(20) - OBRIGATORIO
EMAIL - CARACTER(30)
ENDERECO
CIDADE
ESTADO - CARACTER(2)
TELEFONE - CARACTER(13)
DATA DE CADASTRO
CATEGORIA [SUPERMERCADO, RESTAURANTE, BORRACHARIA, POSTO, OFICINA];
STATUS [ATIVO, INATIVO]
AGENCIA - CARACTER(5)
CONTA - CARACTER(8)
*/

/* MODELO FISICO */

/* CRIAÇÃO DA DATABASE */

CREATE DATABASE FITCARD;

/* CONECTAR AO BANCO */

USE FITCARD;

/* CRIAÇÃO DE TABELAS */

CREATE TABLE ESTABELECIMENTO(
	IDESTABELECIMENTO INT PRIMARY KEY AUTO_INCREMENT,
	CNPJ VARCHAR(18) NOT NULL,
	RAZAO_SOCIAL VARCHAR(60) NOT NULL,
	NOME_FANTASIA VARCHAR(60),
	EMAIL VARCHAR(45) UNIQUE,
	AGENCIA VARCHAR(5),
	CONTA VARCHAR(8),
	CATEGORIA ENUM('S', 'R', 'B', 'P', 'O'),
	STATUS ENUM('A', 'I'),
	DATA_CADASTRO DATE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	DDD CHAR(4) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ESTABELECIMENTO INT
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30),
	NUM VARCHAR(5),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_ESTABELECIMENTO INT UNIQUE
);

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	USUARIO VARCHAR(30) UNIQUE,
	SENHA VARCHAR(255)
);

/* INSERE USUARIO */

INSERT INTO USUARIO (USUARIO, SENHA) VALUES ('admin', '123');

/* CONSTRAINTS */

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_ESTABELECIMENTO
FOREIGN KEY(ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTO(IDESTABELECIMENTO) ON DELETE CASCADE;


ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ESTABELECIMENTO
FOREIGN KEY(ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTO(IDESTABELECIMENTO) ON DELETE CASCADE;



