<!DOCTYPE html>
<html>

<head>
    <base href="<?php echo APP_ROOT; ?>">
    <title>Acesso Restrito - Portal Fitcard</title>
    <link href="content\assets\bootstrap\css\bootstrap.min.css" type="text/css" rel="stylesheet">
    <link href="content/portal/css/style.login.css" type="text/css" rel="stylesheet">
    <link href="content/assets/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
</head>

<body>
    <?php $this->render(); ?>
    <script src="content\assets\jquery-3.3.1.min.js"></script>
    <script src="content\assets\bootstrap\js\bootstrap.min.js"></script>
</body>

</html>