<!DOCTYPE html>
<html>

<head>
    <base href="<?php echo APP_ROOT; ?>">
    <title><?php echo $this->title; ?></title>
    <link rel="shortcut icon" type="image/png" href="content/portal/imgs/favicon.png">
    <link href="content\assets\bootstrap\css\bootstrap.min.css" type="text/css" rel="stylesheet">
    <link href="content/portal/css/style.css" type="text/css" rel="stylesheet">
    <link href="content/assets/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
</head>

<body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-fitcard">
      <a class="navbar-brand" href="portal"><img src="content/portal/imgs/fitcard-logo.png" alt="Fitcard Logo" width="121" height="30"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="portal/estabelecimento/">Estabelecimentos <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="portal/sessao/logout" method="post">
          <button class="btn btn-outline-danger btn-sair my-2 my-sm-0" type="submit"><i class="fas fa-sign-out-alt btn-icon"></i>Sair</button>
        </form>
      </div>
    </nav>
        <?php $this->render(); ?>
    </div>
    <script src="content\assets\jquery-3.3.1.min.js"></script>
    <script src="content\assets\bootstrap\js\bootstrap.min.js"></script>
    <script src="content/assets/vanilla-masker/vanilla-masker.min.js"></script>
    <script src="content\portal\notify.min.js"></script>
    <?php if ($view_salvo == "true"): ?>
      <script>
        $.notify("Estabelecimento salvo com sucesso!", "success");
      </script>
    <?php elseif ($view_removido == "true"): ?>
      <script>
        $.notify("Estabelecimento removido com sucesso!", "success");
      </script>
    <?php else: ?>

    <?php endif; ?>
  </body>

</html>