<form action="portal/estabelecimento/save" id="formEstabelecimento" onsubmit="return validarForm()" name="form_estabelecimento" method="POST">
    
    <div class="form-group">
        <label>Categoria</label>
        <select class="form-control" name="categoria" onchange="verificaCategoria(this.value)">
            <option value="B">Borracharia</option>
            <option value="O">Oficina</option>
            <option value="O">Posto</option>
            <option value="R">Restaurante</option>
            <option value="S">Supermercado</option>
        </select>
    </div>

    <div class="form-group">
        <label>Razão Social</label>
        <input type="text" class="form-control" name="razao_social" id="razaoSocial" required>
    </div>
    
    <div class="form-group">
        <label>CNPJ</label>
        <input type="text" class="form-control" required onchange="validarCNPJ(this.value)" id="cnpj" name="cnpj">
    </div>

    <div class="form-group">
        <label>Nome Fantasia</label>
        <input type="text" class="form-control" name="nome_fantasia">
    </div>
    
    <div class="form-group">
        <label>Email</label>
        <input type="text" class="form-control" id="email" onchange="validarEmail(this.value)" name="email">
    </div>

    <div class="row">
        <div class="col-sm-3">
            <label>DDD</label>
            <input type="text" class="form-control" id="ddd" name="ddd">
        </div>

        <div class="col-sm-9">
            <label>TELEFONE</label>
            <input type="text" class="form-control" id="numTelefone" name="numero">
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                <label>AGÊNCIA</label>
                <input type="text" class="form-control" id="agencia" name="agencia">
            </div>

            <div class="col-sm-6">
                <label>CONTA</label>
                <input type="text" class="form-control" id="conta" name="conta">
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                <label>RUA</label>
                <input type="text" class="form-control" name="rua">
            </div>

            <div class="col-sm-1">
                <label>NUM</label>
                <input type="text" class="form-control" name="num">
            </div>

            <div class="col-sm-5">
                <label>BAIRRO</label>
                <input type="text" class="form-control" name="bairro">
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                <label>CIDADE</label>
                <input type="text" class="form-control" name="cidade">
            </div>
            <div class="col-sm-6">
                <label>ESTADO</label>
                <select class="form-control" name="estado">
                    <option value="AC">AC</option>
                    <option value="AL">AL</option>
                    <option value="AM">AM</option>
                    <option value="AP">AP</option>
                    <option value="BA">BA</option>
                    <option value="CE">CE</option>
                    <option value="DF">DF</option>
                    <option value="ES">ES</option>
                    <option value="GO">GO</option>
                    <option value="MA">MA</option>
                    <option value="MT">MT</option>
                    <option value="MS">MS</option>
                    <option value="MG">MG</option>
                    <option value="PA">PA</option>
                    <option value="PB">PB</option>
                    <option value="PR">PR</option>
                    <option value="PE">PE</option>
                    <option value="PI">PI</option>
                    <option value="RJ">RJ</option>
                    <option value="RN">RN</option>
                    <option value="RS">RS</option>
                    <option value="RO">RO</option>
                    <option value="RR">RR</option>
                    <option value="SC">SC</option>
                    <option value="SP">SP</option>
                    <option value="SE">SE</option>
                    <option value="TO">TO</option>
                </select>
            </div>
        </div>
    </div>
    
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="status" id="status1" value="A" checked>
        <label class="form-check-label" for="status1">
            Ativo
        </label>
    </div>

    <div class="form-group">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="status2" value="I">
            <label class="form-check-label" for="status2">
                Inativo
            </label>
        </div>
    </div>

    <div class="form-group">
        <a href="portal/estabelecimento" class="btn btn-outline-info"><i class="far fa-arrow-alt-circle-left btn-icon"></i>Voltar</a>
        <div class="float-right">
            <button class="btn btn-outline-success" type="submit"><i class="far fa-save btn-icon"></i>Salvar</button>
        </div>
        
    </div>
</form>


