<form action="portal/estabelecimento/save" id="formEstabelecimento" name="form_estabelecimento" onsubmit="return validarForm()" method="POST">

    <div class="form-group">
        <label>ID do Estabelecimento</label>
        <input type="text" class="form-control" readonly name="idestabelecimento" value="<?php echo $view_dados->idestabelecimento; ?>">
    </div>

    <div class="form-group">
        <label>Categoria</label>
        <select class="form-control" name="categoria" onchange="verificaCategoria(this.value)">
            <option <?php echo $view_dados->categoria == "B" ? "selected" : ""; ?> value="B">Borracharia</option>
            <option <?php echo $view_dados->categoria == "O" ? "selected" : ""; ?> value="O">Oficina</option>
            <option <?php echo $view_dados->categoria == "O" ? "selected" : ""; ?> value="O">Posto</option>
            <option <?php echo $view_dados->categoria == "R" ? "selected" : ""; ?> value="R">Restaurante</option>
            <option <?php echo $view_dados->categoria == "S" ? "selected" : ""; ?> value="S">Supermercado</option>
        </select>
    </div>

    <div class="form-group">
        <label>Razão Social</label>
        <input type="text" class="form-control" name="razao_social" value="<?php echo $view_dados->razao_social; ?>">
    </div>
    
    <div class="form-group">
        <label>CNPJ</label>
        <input type="text" class="form-control" onchange="validarCNPJ(this.value)" id="cnpj" name="cnpj" value="<?php echo $view_dados->cnpj; ?>">
    </div>

    <div class="form-group">
        <label>Nome Fantasia</label>
        <input type="text" class="form-control" name="nome_fantasia" value="<?php echo $view_dados->nome_fantasia; ?>">
    </div>
    
    <div class="form-group">
        <label>Email</label>
        <input type="text" class="form-control" id="email" onchange="validarEmail(this.value)" name="email" value="<?php echo $view_dados->email; ?>">
    </div>

    <div class="row">
        <div class="col-sm-3">
            <label>DDD</label>
            <input type="text" class="form-control" id="ddd" name="ddd" value="<?php echo $view_dados->ddd; ?>">
        </div>

        <div class="col-sm-9">
            <label>TELEFONE</label>
            <input type="text" class="form-control" id="numTelefone" name="numero" value="<?php echo $view_dados->numero; ?>">
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                <label>AGÊNCIA</label>
                <input type="text" class="form-control" id="agencia" name="agencia" value="<?php echo $view_dados->agencia; ?>">
            </div>

            <div class="col-sm-6">
                <label>CONTA</label>
                <input type="text" class="form-control" id="conta" name="conta" value="<?php echo $view_dados->conta; ?>">
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                <label>RUA</label>
                <input type="text" class="form-control" name="rua" value="<?php echo $view_dados->rua; ?>">
            </div>

            <div class="col-sm-1">
                <label>NUM</label>
                <input type="text" class="form-control" name="num" value="<?php echo $view_dados->num; ?>">
            </div>

            <div class="col-sm-5">
                <label>BAIRRO</label>
                <input type="text" class="form-control" name="bairro" value="<?php echo $view_dados->bairro; ?>">
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-sm-6">
                <label>CIDADE</label>
                <input type="text" class="form-control" name="cidade" value="<?php echo $view_dados->cidade; ?>">
            </div>
            <div class="col-sm-3">
                <label>ESTADO</label>
                <select class="form-control" name="estado">
                    <option <?php echo $view_dados->estado == "AC" ? "selected" : ""; ?> value="AC">AC</option>
                    <option <?php echo $view_dados->estado == "AL" ? "selected" : ""; ?> value="AL">AL</option>
                    <option <?php echo $view_dados->estado == "AM" ? "selected" : ""; ?> value="AM">AM</option>
                    <option <?php echo $view_dados->estado == "AP" ? "selected" : ""; ?> value="AP">AP</option>
                    <option <?php echo $view_dados->estado == "BA" ? "selected" : ""; ?> value="BA">BA</option>
                    <option <?php echo $view_dados->estado == "CE" ? "selected" : ""; ?> value="CE">CE</option>
                    <option <?php echo $view_dados->estado == "DF" ? "selected" : ""; ?> value="DF">DF</option>
                    <option <?php echo $view_dados->estado == "ES" ? "selected" : ""; ?> value="ES">ES</option>
                    <option <?php echo $view_dados->estado == "GO" ? "selected" : ""; ?> value="GO">GO</option>
                    <option <?php echo $view_dados->estado == "MA" ? "selected" : ""; ?> value="MA">MA</option>
                    <option <?php echo $view_dados->estado == "MT" ? "selected" : ""; ?> value="MT">MT</option>
                    <option <?php echo $view_dados->estado == "MS" ? "selected" : ""; ?> value="MS">MS</option>
                    <option <?php echo $view_dados->estado == "MG" ? "selected" : ""; ?> value="MG">MG</option>
                    <option <?php echo $view_dados->estado == "PA" ? "selected" : ""; ?> value="PA">PA</option>
                    <option <?php echo $view_dados->estado == "PB" ? "selected" : ""; ?> value="PB">PB</option>
                    <option <?php echo $view_dados->estado == "PR" ? "selected" : ""; ?> value="PR">PR</option>
                    <option <?php echo $view_dados->estado == "PE" ? "selected" : ""; ?> value="PE">PE</option>
                    <option <?php echo $view_dados->estado == "PI" ? "selected" : ""; ?> value="PI">PI</option>
                    <option <?php echo $view_dados->estado == "RJ" ? "selected" : ""; ?> value="RJ">RJ</option>
                    <option <?php echo $view_dados->estado == "RN" ? "selected" : ""; ?> value="RN">RN</option>
                    <option <?php echo $view_dados->estado == "RS" ? "selected" : ""; ?> value="RS">RS</option>
                    <option <?php echo $view_dados->estado == "RO" ? "selected" : ""; ?> value="RO">RO</option>
                    <option <?php echo $view_dados->estado == "RR" ? "selected" : ""; ?> value="RR">RR</option>
                    <option <?php echo $view_dados->estado == "SC" ? "selected" : ""; ?> value="SC">SC</option>
                    <option <?php echo $view_dados->estado == "SP" ? "selected" : ""; ?> value="SP">SP</option>
                    <option <?php echo $view_dados->estado == "SE" ? "selected" : ""; ?> value="SE">SE</option>
                    <option <?php echo $view_dados->estado == "TO" ? "selected" : ""; ?> value="TO">TO</option>
                </select>
            </div>
            <div class ="col-sm-3">
                <label>DATA DE CADASTRO</label>
                <input type="text" class="form-control" name="data_cadastro" value="<?php echo formatarData($view_dados->data_cadastro); ?>" readonly>
            </div>
        </div>
    </div>
    
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="status" id="status1" value="A" <?php echo $view_dados->status == "A" ? "checked" : "" ?>>
        <label class="form-check-label" for="status1">
            Ativo
        </label>
    </div>

    <div class="form-group">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="status2" value="I" <?php echo $view_dados->status == "I" ? "checked" : "" ?>>
            <label class="form-check-label" for="status2">
                Inativo
            </label>
        </div>
    </div>

    <div class="form-group">
        <a href="portal/estabelecimento" class="btn btn-outline-info"><i class="far fa-arrow-alt-circle-left btn-icon"></i>Voltar</a>
        <div class="float-right">
            <a href="portal/estabelecimento/delete/<?php echo $view_dados->idestabelecimento; ?>" class="btn btn-outline-danger"><i class="far fa-trash-alt btn-icon"></i>Deletar</a>
            <button class="btn btn-outline-success" type="submit"><i class="far fa-save btn-icon"></i>Salvar</button>
        </div>
        
    </div>
</form>



