<div class="wrapper">
    <div class="middle">
        <form action="portal/sessao/validar" method="post">
        <img src="content/portal/imgs/fitcard-logo.png" alt="Fitcard Logo" width="170" height="42">
            <div class="form-group">
                <label>Usuário</label>
                <input type="text" name="usuario" class="form-control">
            </div>
            <div class="form-group">
                <label>Senha</label>
                <input type="password" name="senha" class="form-control">
            </div>
            <button type="submit" name="logar" class="btn btn-sm btn-info btn-login"><i class="fas fa-sign-in-alt icon-btn"></i>Entrar</button>
        </form>
    </div>
</div>
